name: Python CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'
    - name: Install UV
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        uv venv
        echo "$(pwd)/.venv/bin" >> $GITHUB_PATH
        uv pip install -e .
    - name: Lint with Ruff
      run: |
        uv pip install ruff
        ruff check .
        ruff format --check .
    - name: Run tests
      run: |
        uv pip install pytest pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Security check with Ruff
      run: |
        ruff check . --select=S

  docker:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: .devcontainer/Dockerfile
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: .devcontainer/Dockerfile
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
