name: Docker Lint CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  docker-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: .devcontainer/Dockerfile
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: .devcontainer/Dockerfile
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
