name: Docker Lint CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  docker-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: image=moby/buildkit:latest
        buildkitd-flags: --debug
    
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: datascience/.devcontainer/Dockerfile
        ignore: SC1091,DL3008,DL3013
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: datascience/.devcontainer/Dockerfile
        push: false
        load: true
